/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI specification */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI spec in YAML format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site-wide usage stats
         * @description Aggregate totals across every tenant — not scoped to the caller's session. Public and unauthenticated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current usage totals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            documents_indexed?: number;
                            avg_document_size_bytes?: number;
                            queries_executed?: number;
                            avg_query_duration_ms?: number;
                            sessions_created?: number;
                            sessions_swept?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current session's expiry status
         * @description Backs the in-app warning banner. warning_active becomes true within the final warning window before the session is swept; deletes_at is the earlier of the idle-timeout expiry and the hard-cap expiry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account TTL status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            warning_active: boolean;
                            /** Format: date-time */
                            deletes_at: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge bases */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Cursor — UUID of the last item from the previous page */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of knowledge bases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KBPage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a knowledge base */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Knowledge base created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a knowledge base */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Knowledge base */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a knowledge base */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename a knowledge base */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Updated knowledge base */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/kbs/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search a knowledge base */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        query: string;
                    };
                };
            };
            responses: {
                /** @description A Server-Sent Events stream, not a single JSON body — OpenAPI has no first-class way to express this, so the shape is documented here instead of in `content`. Frames arrive in this order: exactly one "retrieved_files" event (SearchRetrievedFilesEvent) once retrieval finishes, then zero or more "delta" events (SearchDeltaEvent) as the answer is generated, then exactly one of "done" (SearchDoneEvent) or "error" (SearchErrorEvent, only possible once streaming has already started — see the 500 response for a failure before that point). Each frame is `event: <name>\ndata: <json>\n\n`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Search failed before any event was streamed (e.g. retrieval itself failed) — a normal JSON error, since nothing has been written yet at this point. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a knowledge base's most recent community-detection result
         * @description Returns a zero-value result (null computed_at) rather than a 404 when community detection has never been run for this knowledge base yet — that's a normal first-run state, not an error.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The knowledge base's community-detection summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Recompute community detection over a knowledge base's entity graph
         * @description Manually triggered, synchronous: runs Louvain community detection over the canonical-entity graph and fully replaces the previous result. Not run automatically on document upload/delete.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new community-detection summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The knowledge base has too many canonical entities to compute communities synchronously. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Community detection did not finish within the configured deadline. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a knowledge base's most recently generated theme labels
         * @description Returns a zero-value result (null computed_at, empty themes) rather than a 404 when themes have never been generated for this knowledge base yet — that's a normal first-run state, not an error.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The knowledge base's theme labels. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemeResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Generate short LLM labels for a knowledge base's largest entity communities
         * @description Manually triggered: selects the largest communities found by the most recent community-detection run and generates a short label and one-sentence summary for each, fully replacing whatever themes were there before. Requires community detection to have already been run at least once for this knowledge base.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The newly generated theme labels. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemeResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Community detection has never been run for this knowledge base, so there are no communities to generate themes from. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/intrusion-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a knowledge base's most recently run intrusion test result
         * @description Returns a zero-value result (null computed_at, empty communities) rather than a 404 when an intrusion test has never been run for this knowledge base yet — that's a normal first-run state, not an error.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The knowledge base's most recent intrusion test result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntrusionTestResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Run a word/topic intrusion test over a knowledge base's current community structure
         * @description Manually triggered: for each of up to 30 communities large enough to test, mixes a few of its real top members with one entity taken from a different community and asks an LLM judge to spot the intruder. The fraction of communities where the judge succeeds is a quantitative coherence metric for the current community structure, meant for comparing before/after a pipeline change (chunking, edge weighting, entity filtering) rather than eyeballing examples. Sampling and intruder selection are deterministic for a given community structure, so re-running this against unchanged data always produces the same score. Fully replaces whatever result was there before. Requires community detection to have already been run at least once for this knowledge base.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The newly computed intrusion test result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntrusionTestResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Community detection has never been run for this knowledge base, so there is no community structure to test. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review a bounded batch of not-yet-checked co-occurrence edges for an actual relationship
         * @description For up to a small, fixed number of chunks that still have a co-occurrence edge with no relation type, asks an LLM whether the source text actually supports a specific relationship for each candidate pair (e.g. "founded", "works at") -- and if not, marks it reviewed with no relationship found, so it isn't asked about again. Incremental and idempotent: reviewing a knowledge base in full is a matter of calling this endpoint repeatedly, not raising any limit. Returns a zero-value summary (not an error) once every pair has already been reviewed, or if none exist yet.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Summary of this run. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelationExtractionResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a knowledge base's canonical-entity graph, shaped for display
         * @description Returns every canonical entity as a node (with its current community_id and degree) and every aggregated co-occurrence edge. Does not compute anything -- community_id reflects whatever the most recent POST /kbs/{id}/communities run assigned, null if that has never run.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The knowledge base's graph. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/inquiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the researcher's Inquiry (turn history) for a knowledge base
         * @description Returns an empty Inquiry (null id, no messages) rather than a 404 when no search has been run against this knowledge base yet — that's a normal state, not an error.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The Inquiry for this knowledge base. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inquiry"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{id}/inquiry/messages/{messageId}/reevaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run the query behind a past assistant message against the current knowledge base state
         * @description Appends a new assistant message rather than overwriting the original — seeing that an answer changed is often as valuable as the new answer itself. messageId must identify an assistant-role message in the caller's Inquiry for this knowledge base; the query re-run is the content of the user message that originally prompted it. Same event stream shape as POST /kbs/{id}/search.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A Server-Sent Events stream identical in shape to POST /kbs/{id}/search's 200 response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description messageId does not identify a re-evaluatable assistant message (unknown, a user-role message, or the first message in the inquiry). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found, or no Inquiry exists yet for it. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Search failed before any event was streamed — a normal JSON error, since nothing has been written yet at this point. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{kbId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        /** List documents in a knowledge base */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Cursor — UUID of the last item from the previous page */
                    after?: string;
                };
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of documents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentPage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a document
         * @description Accepts .txt and .md files (text pipeline) plus .pdf, .png, .jpg (region- classification pipeline: pdfplumber + unstructured.io layout analysis).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Document created and queued for indexing */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unsupported file type */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{kbId}/documents/{docId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        /** Get a document (including its status) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Document is being indexed and cannot be deleted yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{kbId}/documents/{docId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-enqueue a dead-lettered (failed) document for processing
         * @description Reuses the object already in storage — no re-upload needed. Only valid for a document whose status is "failed"; anything else returns 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document reset to pending and re-enqueued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Document is not in a failed state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{kbId}/documents/{docId}/retry-entity-extraction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run just entity extraction for an already-indexed document
         * @description Unlike POST .../retry (which requires status "failed" and re-runs the whole pipeline from upload), this only requires status "indexed" and re-publishes the entity-extraction stage alone — chunking and embedding are untouched, and document status doesn't change. Safe to call repeatedly: each run fully replaces the document's previously extracted entities rather than accumulating duplicates.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entity extraction re-enqueued; document unchanged. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Document is not indexed yet (no chunks to extract entities from), or an entity-extraction job is already active for it. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kbs/{kbId}/documents/{docId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        /** Get the raw text content of a document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw document text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kb_id: string;
            /** Format: uuid */
            user_id: string;
            filename: string;
            s3_key: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** @enum {string} */
            status: "pending" | "processing" | "indexed" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Set for PDF/image documents once region classification has run. Omitted for text/markdown documents and before classification completes. */
            manifest_summary?: {
                indexed: number;
                skipped: number;
                failed: number;
            } | null;
            /** @description Staged ingestion checklist, always ending on a "complete" stage. Set for every status except failed (a dead-lettered document has nothing left to report), and omitted entirely on responses where per-document progress isn't available. Stays set forever once a document finishes its whole pipeline -- including background entity extraction, which keeps running after the document is already searchable -- so it doubles as a permanent ingestion-history record, not just live progress. */
            progress?: {
                stages: {
                    key: string;
                    label: string;
                    message?: string;
                }[];
                /** @description Every stages[].key currently in progress, in canonical stage order. More than one can be present at once: entity extraction can start before a document's own indexing job finishes, so e.g. "embedding" and "entities" can both be genuinely active for the same document simultaneously -- this is reported honestly rather than collapsed to a single stage. Empty when the document is queued but no worker has picked it up yet. Permanently ["complete"] once the whole pipeline, including background entity extraction, has finished. */
                active_stages?: string[];
            } | null;
        };
        Citation: {
            /** @description The 1-indexed [N] marker this citation corresponds to in the summary text. Match markers to citations by this field, not by array position — the list is sparse whenever the model didn't cite every numbered source chunk. */
            number: number;
            /** Format: uuid */
            document_id: string;
            /** Format: uuid */
            chunk_id: string;
            char_start: number;
            char_end: number;
            /** @description The source document's filename — the entire primary citation identity, plus locator when present. Citations are grouped and displayed by file, not by individual chunk text, mirroring how search engines cite the source page rather than a byte range within it. */
            file_name: string;
            /** @description An optional modality-native locator narrowing the citation within the file — a page number for PDF-derived chunks. Absent for plain-text/markdown chunks. Shaped so a future locator type (e.g. a video timestamp) is an additive change, not a schema rework. */
            locator: {
                /** @enum {string} */
                type: "page";
                value: number;
            } | null;
        };
        /** @description Payload of the "retrieved_files" SSE event: fires once, before generation begins. */
        SearchRetrievedFilesEvent: {
            /** @description Every file the fused top-k retrieval surfaced, ranked, whether or not it ends up cited inline in the eventual summary — a superset of the files named in the done event's citations. */
            retrieved_files: components["schemas"]["RetrievedFile"][];
        };
        /** @description Payload of a "delta" SSE event: one chunk of the generated answer text, in the order generated. Zero or more of these fire between retrieved_files and done. */
        SearchDeltaEvent: {
            text: string;
        };
        /** @description Payload of the final "done" SSE event: the complete, parsed answer. retrieved_files isn't repeated here — it already went out as its own event. */
        SearchDoneEvent: {
            summary: string;
            citations: components["schemas"]["Citation"][];
        };
        /** @description Payload of an "error" SSE event, sent only when the search fails after streaming has already started (so the HTTP status can no longer change to reflect the failure). */
        SearchErrorEvent: {
            error: string;
        };
        RetrievedFile: {
            /** Format: uuid */
            document_id: string;
            file_name: string;
        };
        /** @description One turn in an Inquiry: either the researcher's query (role=user, no citations/retrieved_documents) or a generated answer (role=assistant). Answers are never overwritten — a re-evaluation appends a new message with supersedes_message_id set rather than replacing the one it re-answers. */
        InquiryMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            citations: components["schemas"]["Citation"][];
            retrieved_documents: components["schemas"]["RetrievedFile"][];
            /** Format: uuid */
            supersedes_message_id: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description The researcher's single persisted thread of turns for one knowledge base. id is nullable: a knowledge base with no searches run against it yet has no Inquiry, which is a normal state, not an error. */
        Inquiry: {
            /** Format: uuid */
            id: string | null;
            messages: components["schemas"]["InquiryMessage"][];
        };
        /** @description A knowledge base's most recent Louvain community-detection run. computed_at is null when detection has never been run for this knowledge base — a normal first-run state, not an error. */
        CommunityResult: {
            /** Format: date-time */
            computed_at: string | null;
            modularity: number;
            community_count: number;
            node_count: number;
            edge_count: number;
        };
        /** @description One LLM-generated label/summary for a notable community. community_id is only meaningful relative to the community-detection run active when this theme was generated. */
        Theme: {
            community_id: number;
            label: string;
            summary: string;
            entity_count: number;
        };
        /** @description A knowledge base's most recently generated theme labels. computed_at is null when themes have never been generated for this knowledge base — a normal first-run state, not an error. */
        ThemeResult: {
            /** Format: date-time */
            computed_at: string | null;
            themes: components["schemas"]["Theme"][];
            /** @description A one-line explanation of what set the returned themes apart, present only when the knowledge base has more community structure than what's shown here. Only ever populated on the response to POST — it explains that specific recompute's output and isn't persisted, so GET never includes it. */
            note?: string;
        };
        /** @description One tested community's word/topic intrusion test outcome: a handful of its real members were shown to a judge alongside one entity deliberately taken from a different community (the intruder), and the judge was asked to spot which one doesn't belong. */
        IntrusionTestCommunity: {
            community_id: number;
            members: string[];
            intruder_text: string;
            judge_answer: string;
            correct: boolean;
        };
        /** @description A knowledge base's most recent intrusion test run -- a quantitative coherence metric for its detected communities. computed_at is null and communities is empty when a test has never been run, or when fewer than two communities were large enough to test. */
        IntrusionTestResult: {
            /** Format: date-time */
            computed_at: string | null;
            /** @description Correct / tested_count, in [0, 1]. Zero when tested_count is zero. */
            score: number;
            tested_count: number;
            communities: components["schemas"]["IntrusionTestCommunity"][];
        };
        /** @description Summary of one relation-extraction run: how many not-yet-checked co-occurrence edges were reviewed, and how many of those the model found an actual relationship for versus none. pairs_reviewed can exceed relations_found + none_count if the model's response didn't address every pair -- those are simply left for a later run. */
        RelationExtractionResult: {
            chunks_reviewed: number;
            pairs_reviewed: number;
            relations_found: number;
            none_count: number;
        };
        /** @description One canonical entity in a knowledge base's graph view. community_id is null if community detection has never been run, or ran before this entity existed. */
        GraphNode: {
            /** Format: uuid */
            id: string;
            label: string;
            type: string;
            community_id: number | null;
            degree: number;
            /** @description Number of distinct documents contributing at least one mention of this entity — a signal of cross-document overlap in a knowledge base with more than one source. */
            document_count: number;
        };
        /** @description One aggregated co-occurrence edge between two canonical entities. */
        GraphEdge: {
            /** Format: uuid */
            source: string;
            /** Format: uuid */
            target: string;
            weight: number;
            /** @description Number of distinct documents whose chunks contributed a co-occurrence to this pair. */
            document_count: number;
            /** @description The actual relationship found between these two entities (e.g. "founded", "works at"), null if relation extraction hasn't reviewed this pair yet or found no clear relationship in the source text. */
            relation_type: string | null;
        };
        /** @description A knowledge base's canonical-entity graph, shaped for display — every canonical entity as a node and every aggregated co-occurrence edge. Unfiltered; percentile-based server-side filtering is a later refinement, not yet applied here. */
        GraphView: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        KBPage: {
            items: components["schemas"]["KnowledgeBase"][];
            next_cursor?: string | null;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            next_cursor?: string | null;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
