/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI specification */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI spec in YAML format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current session's expiry status
         * @description Backs the in-app warning banner. warning_active becomes true within the final warning window before the session is swept; deletes_at is the earlier of the idle-timeout expiry and the hard-cap expiry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account TTL status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            warning_active: boolean;
                            /** Format: date-time */
                            deletes_at: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge bases */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Cursor — UUID of the last item from the previous page */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of knowledge bases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KBPage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a knowledge base */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Knowledge base created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a knowledge base */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Knowledge base */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a knowledge base */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename a knowledge base */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Updated knowledge base */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeBase"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/kbs/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search a knowledge base */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        query: string;
                    };
                };
            };
            responses: {
                /** @description A Server-Sent Events stream, not a single JSON body — OpenAPI has no first-class way to express this, so the shape is documented here instead of in `content`. Frames arrive in this order: exactly one "retrieved_files" event (SearchRetrievedFilesEvent) once retrieval finishes, then zero or more "delta" events (SearchDeltaEvent) as the answer is generated, then exactly one of "done" (SearchDoneEvent) or "error" (SearchErrorEvent, only possible once streaming has already started — see the 500 response for a failure before that point). Each frame is `event: <name>\ndata: <json>\n\n`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Search failed before any event was streamed (e.g. retrieval itself failed) — a normal JSON error, since nothing has been written yet at this point. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs/{kbId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        /** List documents in a knowledge base */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Cursor — UUID of the last item from the previous page */
                    after?: string;
                };
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of documents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentPage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a document
         * @description Accepts .txt and .md files (text pipeline) plus .pdf, .png, .jpg (region- classification pipeline: pdfplumber + unstructured.io layout analysis).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Document created and queued for indexing */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Knowledge base not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unsupported file type */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs/{kbId}/documents/{docId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        /** Get a document (including its status) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Document is being indexed and cannot be deleted yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs/{kbId}/documents/{docId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-enqueue a dead-lettered (failed) document for processing
         * @description Reuses the object already in storage — no re-upload needed. Only valid for a document whose status is "failed"; anything else returns 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document reset to pending and re-enqueued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Document is not in a failed state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kbs/{kbId}/documents/{docId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                docId: string;
            };
            cookie?: never;
        };
        /** Get the raw text content of a document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    docId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw document text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kb_id: string;
            /** Format: uuid */
            user_id: string;
            filename: string;
            s3_key: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** @enum {string} */
            status: "pending" | "processing" | "indexed" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Set for PDF/image documents once region classification has run. Omitted for text/markdown documents and before classification completes. */
            manifest_summary?: {
                indexed: number;
                skipped: number;
                failed: number;
            } | null;
        };
        Citation: {
            /** @description The 1-indexed [N] marker this citation corresponds to in the summary text. Match markers to citations by this field, not by array position — the list is sparse whenever the model didn't cite every numbered source chunk. */
            number: number;
            /** Format: uuid */
            document_id: string;
            /** Format: uuid */
            chunk_id: string;
            char_start: number;
            char_end: number;
            /** @description The cited chunk's own extracted text, served directly so clients never need to re-fetch and slice the original document. Used as the drill-down evidence behind the primary file+locator citation, not as the primary citation display itself. */
            text: string;
            /** @description The source document's filename. This, plus locator when present, is the primary citation identity — mirroring how search engines cite the source page rather than a byte range within it. */
            file_name: string;
            /** @description An optional modality-native locator narrowing the citation within the file — a page number for PDF-derived chunks. Absent for plain-text/markdown chunks. Shaped so a future locator type (e.g. a video timestamp) is an additive change, not a schema rework. */
            locator: {
                /** @enum {string} */
                type: "page";
                value: number;
            } | null;
        };
        /** @description Payload of the "retrieved_files" SSE event: fires once, before generation begins. */
        SearchRetrievedFilesEvent: {
            /** @description Every file the fused top-k retrieval surfaced, ranked, whether or not it ends up cited inline in the eventual summary — a superset of the files named in the done event's citations. */
            retrieved_files: components["schemas"]["RetrievedFile"][];
        };
        /** @description Payload of a "delta" SSE event: one chunk of the generated answer text, in the order generated. Zero or more of these fire between retrieved_files and done. */
        SearchDeltaEvent: {
            text: string;
        };
        /** @description Payload of the final "done" SSE event: the complete, parsed answer. retrieved_files isn't repeated here — it already went out as its own event. */
        SearchDoneEvent: {
            summary: string;
            citations: components["schemas"]["Citation"][];
        };
        /** @description Payload of an "error" SSE event, sent only when the search fails after streaming has already started (so the HTTP status can no longer change to reflect the failure). */
        SearchErrorEvent: {
            error: string;
        };
        RetrievedFile: {
            /** Format: uuid */
            document_id: string;
            file_name: string;
        };
        KBPage: {
            items: components["schemas"]["KnowledgeBase"][];
            next_cursor?: string | null;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            next_cursor?: string | null;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
