package search

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"github.com/kunalpednekar/dumpster/internal/llm"
	"github.com/kunalpednekar/dumpster/internal/retrieval"
)

// notFoundSummary is returned verbatim when retrieval yields no relevant chunks.
const notFoundSummary = "I could not find relevant information to answer this question."

// LLMAnswerer implements Answerer using a language model Generator.
// It builds a prompt that numbers each source chunk, instructs the model to
// cite claims using [N] markers, and parses a "CITATIONS: 1,2,3" footer to
// resolve which chunks were actually used.
type LLMAnswerer struct {
	gen llm.Generator
}

// NewAnswerer returns an LLMAnswerer backed by gen.
func NewAnswerer(gen llm.Generator) *LLMAnswerer {
	return &LLMAnswerer{gen: gen}
}

// Answer builds a grounding prompt from chunks, calls the Generator, and
// parses the structured response into a Result. If chunks is empty, it
// returns the not-found guardrail immediately without calling the Generator.
func (a *LLMAnswerer) Answer(ctx context.Context, kbID uuid.UUID, query string, chunks []retrieval.ScoredChunk) (Result, error) {
	return a.AnswerStream(ctx, kbID, query, chunks, func(string) {})
}

// AnswerStream behaves like Answer, but also invokes onDelta for each
// visible text chunk as it's generated by the Generator's streaming call.
// A footerFilter sits between the raw generator deltas and onDelta so the
// CITATIONS: footer — which parseResponse needs the complete response to
// find reliably (see its LastIndex comment) — never reaches onDelta, even
// though it isn't fully known to be a footer until later text confirms it.
func (a *LLMAnswerer) AnswerStream(ctx context.Context, _ uuid.UUID, query string, chunks []retrieval.ScoredChunk, onDelta func(string)) (Result, error) {
	if len(chunks) == 0 {
		return Result{Summary: notFoundSummary}, nil
	}

	// Split at the chunks/question boundary, not built as one string --
	// the source-chunk block is the expensive part of this prompt and, for
	// nearby queries against the same knowledge base, is often identical or
	// near-identical call to call (same top-k retrieval), while the
	// question is what genuinely varies. GenerateStreamCached marks the
	// prefix as reusable so a repeat call sharing it verbatim is billed at
	// a fraction of normal input-token price for that portion, instead of
	// paying full price to resend the same chunk text on every query. Real
	// motivation, not speculative: a sustained burst of load-test queries
	// against a small, fixed set of knowledge bases burned ~3M tokens
	// (~$12) in under an hour with no caching at all -- exactly the
	// repeated-prefix shape this is meant to catch.
	prefix := buildCacheablePrefix(chunks)
	suffix := buildDynamicSuffix(query)
	filter := &footerFilter{}
	resp, err := a.gen.GenerateStreamCached(ctx, prefix, suffix, func(delta string) {
		if safe := filter.Write(delta); safe != "" {
			onDelta(safe)
		}
	})
	if err != nil {
		return Result{}, fmt.Errorf("search: generate: %w", err)
	}
	if safe := filter.Flush(); safe != "" {
		onDelta(safe)
	}

	return parseResponse(resp, chunks), nil
}

// buildCacheablePrefix constructs the part of the grounding prompt that's
// stable across nearby queries against the same chunks -- the instructions
// and the numbered [1..N] source chunks themselves, the bulk of this
// prompt's token cost. Concatenated with buildDynamicSuffix's output, this
// produces the exact same text the single-string prompt used to be; the
// split exists only so GenerateStreamCached knows where the reusable part
// ends, not to change what the model is asked.
func buildCacheablePrefix(chunks []retrieval.ScoredChunk) string {
	var sb strings.Builder
	sb.WriteString("You are a knowledge-base assistant. Answer the question using ONLY the source chunks below.\n")
	sb.WriteString("Cite your sources with [N] where N is the chunk number, but group citations at the end of each paragraph, bullet point, or section rather than after every individual sentence — place every chunk number that supports that whole block of text together at its very end, not scattered one after each sentence.\n")
	sb.WriteString("When more than one chunk supports the same block, place their citations immediately adjacent with no space or punctuation between them, e.g. [1][2], not [1] [2] or [1, 2].\n")
	sb.WriteString("If the chunks do not contain enough information, reply with exactly: \"" + notFoundSummary + "\"\n\n")
	sb.WriteString("Source chunks:\n")
	for i, sc := range chunks {
		fmt.Fprintf(&sb, "[%d] (document:%s chars:%d-%d)\n%s\n\n",
			i+1, sc.DocumentID, sc.CharStart, sc.CharEnd, sc.Text)
	}
	return sb.String()
}

// buildDynamicSuffix constructs the part of the grounding prompt that
// genuinely varies per call -- the question itself -- plus the trailing
// citation-format instruction, kept immediately adjacent to the question
// exactly as it was in the original single-string prompt rather than moved
// into the cacheable prefix: instructions placed right before the actual
// task tend to be followed more reliably, and this instruction is small
// enough that caching it specifically wouldn't matter anyway.
func buildDynamicSuffix(query string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Question: %s\n\n", query)
	sb.WriteString("Write your answer using [N] citations, then on a new line write \"CITATIONS: \" followed by a comma-separated list of the chunk numbers you relied on.\n")
	return sb.String()
}

// parseResponse splits the generator output into summary text and cited chunk
// indices. Indices outside [1, len(chunks)] are silently ignored.
//
// Splitting uses LastIndex on the uppercased response so that:
//   - chunk text containing "CITATIONS:" (e.g. academic papers) does not cause
//     a false split — we want the model's footer at the end, not an echo mid-body.
//   - LLM output using "Citations:" (mixed case) is still recognised.
func parseResponse(resp string, chunks []retrieval.ScoredChunk) Result {
	if strings.TrimSpace(resp) == notFoundSummary {
		return Result{Summary: notFoundSummary}
	}

	// Search case-insensitively by lowercasing both sides. ToLower is safe to
	// use for byte-offset computation because lowercasing CITATIONS: (ASCII)
	// is a no-op, and ToLower never increases byte length, preserving offsets
	// into the original string. ToUpper can shrink multi-byte Unicode
	// characters (e.g. ı → I), making idx point to the wrong position.
	const citationsMarker = "citations:"
	idx := strings.LastIndex(strings.ToLower(resp), citationsMarker)
	if idx == -1 {
		return Result{Summary: strings.TrimSpace(resp)}
	}

	summary := strings.TrimSpace(resp[:idx])
	citationsSection := resp[idx+len(citationsMarker):]

	seen := make(map[int]bool)
	var citations []Citation
	for _, raw := range strings.Split(citationsSection, ",") {
		n, err := strconv.Atoi(strings.TrimSpace(raw))
		if err != nil || n < 1 || n > len(chunks) || seen[n] {
			continue
		}
		seen[n] = true
		sc := chunks[n-1]
		c := Citation{
			Number:     n,
			DocumentID: sc.DocumentID,
			ChunkID:    sc.ID,
			CharStart:  sc.CharStart,
			CharEnd:    sc.CharEnd,
			Text:       sc.Text,
		}
		if sc.PageNumber != nil {
			c.PageNumber = sc.PageNumber
		}
		if sc.BoundingBox != nil {
			c.BoundingBox = &CitationBoundingBox{
				X0: sc.BoundingBox.X0,
				Y0: sc.BoundingBox.Y0,
				X1: sc.BoundingBox.X1,
				Y1: sc.BoundingBox.Y1,
			}
		}
		citations = append(citations, c)
	}

	return Result{Summary: summary, Citations: citations}
}
